discord: "https://discord.gg/kuz6EJpuZ9"

# {NAME} for plain username
chat-format: "{DISPLAYNAME}&7: &r{MESSAGE}"

# Or "none" to disable
join-message: "&7{DISPLAYNAME} &7joined the game."
leave-message: "&7{DISPLAYNAME} &7left the game."

tab-header: "{INFO}Welcome to Chival!"
tab-footer: "&7VERSION: {SUCCESS}0.0.2"
