name: Core
version: '${project.version}'
main: au.chival.core.Core
api-version: 1.8.8
commands:
  help:
    usage: /help <tag>
    description: A command used to get help
  fly:
    usage: /fly [player]
    description: A command used to toggle flight
  speed:
    usage: /speed <speed> [player]
    description: A command used to change speed
  rank:
    usage: /rank <player> <ranks>
    description: A command used to change players ranks