name: Core
version: '${project.version}'
main: au.chival.core.Core
api-version: 1.8.8
commands:
  help:
    usage: /help <tag>
    description: A command used to get help
  fly:
    usage: /fly [player]
    description: A command used to toggle flight
  speed:
    usage: /speed <speed> [player]
    description: A command used to change speed
  tab:
    usage: /speed <speed> [player]
    description: A command used to change speed
  sudo:
    usage: /sudo <player> <command>
    description: A command used to run a command as another player
  gmc:
    usage: /gm(c, s, a, sp) [player]
    description: A command used to change gamemodes
    aliases: [gms, gma, gmsp]

permissions:
  chival.help:
    description: Allows the user to use the help command
    default: true
  chival.fly:
    description: Allows the user to use the fly command
  chival.fly.others:
    description: Allows the user to use the fly command on other players
  chival.speed:
    description: Allows the user to use the speed command
  chival.speed.others:
    description: Allows the user to use the speed command on other players
  chival.chatcolor:
    description: Allows the user to use color codes in chat
  chival.sudo:
    description: Allows the user to use the sudo command
  chival.sudo.exempt:
    description: Allows the user to be exempt from the sudo command
  chival.gamemode:
    description: Allows the user to use the gamemode command
  chival.gamemode.others:
    description: Allows the user to use the gamemode command on other players
